create table public.room_types (
  id bigint generated by default as identity primary key,
  slug text not null,
  name text not null,
  description text not null default '',
  nightly_rate numeric(10, 2) not null,
  currency text not null default 'USD',
  total_units integer not null,
  beds smallint not null default 1,
  bathrooms smallint not null default 1,
  is_active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint room_types_slug_key unique (slug),
  constraint room_types_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint room_types_name_not_blank check (btrim(name) <> ''),
  constraint room_types_rate_positive check (nightly_rate > 0),
  constraint room_types_currency_format check (currency ~ '^[A-Z]{3}$'),
  constraint room_types_units_positive check (total_units > 0),
  constraint room_types_beds_positive check (beds > 0),
  constraint room_types_bathrooms_positive check (bathrooms > 0)
);

create table public.room_images (
  id bigint generated by default as identity primary key,
  room_type_id bigint not null references public.room_types(id) on delete cascade,
  storage_path text not null,
  alt_text text not null default '',
  is_primary boolean not null default false,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint room_images_storage_path_key unique (storage_path),
  constraint room_images_storage_path_not_blank check (btrim(storage_path) <> '')
);

create table public.bookings (
  id bigint generated by default as identity primary key,
  confirmation_code text not null,
  room_type_id bigint not null references public.room_types(id) on delete restrict,
  guest_first_name text not null,
  guest_last_name text not null,
  guest_email text not null,
  guest_phone text not null,
  arrival_date date not null,
  departure_date date not null,
  status text not null default 'pending',
  nightly_rate numeric(10, 2) not null,
  total_amount numeric(12, 2) not null,
  currency text not null default 'USD',
  admin_notes text,
  status_updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bookings_confirmation_code_key unique (confirmation_code),
  constraint bookings_confirmation_code_format check (confirmation_code ~ '^NYK-[A-F0-9]{10}$'),
  constraint bookings_guest_first_name_not_blank check (btrim(guest_first_name) <> ''),
  constraint bookings_guest_last_name_not_blank check (btrim(guest_last_name) <> ''),
  constraint bookings_guest_email_format check (
    guest_email = lower(guest_email)
    and guest_email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
  ),
  constraint bookings_guest_phone_not_blank check (btrim(guest_phone) <> ''),
  constraint bookings_valid_stay check (departure_date > arrival_date),
  constraint bookings_status_valid check (
    status in ('pending', 'confirmed', 'rejected', 'cancelled', 'completed')
  ),
  constraint bookings_rate_positive check (nightly_rate > 0),
  constraint bookings_total_positive check (total_amount > 0),
  constraint bookings_currency_format check (currency ~ '^[A-Z]{3}$')
);

create index room_types_active_display_order_idx
  on public.room_types (is_active, display_order, id);

create index room_images_room_order_idx
  on public.room_images (room_type_id, display_order, id);

create unique index room_images_one_primary_per_room_idx
  on public.room_images (room_type_id)
  where is_primary;

create index bookings_reserved_overlap_idx
  on public.bookings (room_type_id, arrival_date, departure_date)
  where status in ('pending', 'confirmed');

create index bookings_status_created_idx
  on public.bookings (status, created_at desc);

create index bookings_guest_email_idx
  on public.bookings (lower(guest_email), created_at desc);

create index bookings_recent_idx
  on public.bookings (created_at desc);

create index bookings_status_arrival_idx
  on public.bookings (status, arrival_date);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create or replace function public.set_booking_timestamps()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at := now();
  if new.status is distinct from old.status then
    new.status_updated_at := now();
  end if;
  return new;
end;
$$;

create trigger room_types_set_updated_at
before update on public.room_types
for each row execute function public.set_updated_at();

create trigger room_images_set_updated_at
before update on public.room_images
for each row execute function public.set_updated_at();

create trigger bookings_set_timestamps
before update on public.bookings
for each row execute function public.set_booking_timestamps();

create or replace function public.is_admin()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin';
$$;

create or replace function public.create_booking_request(
  p_room_type_id bigint,
  p_guest_first_name text,
  p_guest_last_name text,
  p_guest_email text,
  p_guest_phone text,
  p_arrival_date date,
  p_departure_date date
)
returns table (
  booking_confirmation_code text,
  booking_status text,
  booked_nightly_rate numeric,
  booking_total_amount numeric,
  booking_currency text,
  remaining_units integer
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_room public.room_types%rowtype;
  v_reserved integer;
  v_confirmation text;
  v_total numeric(12, 2);
  v_attempt integer := 0;
begin
  if p_arrival_date is null
    or p_departure_date is null
    or p_departure_date <= p_arrival_date
    or p_arrival_date < current_date then
    raise exception using
      errcode = '22023',
      message = 'INVALID_STAY_DATES';
  end if;

  if btrim(coalesce(p_guest_first_name, '')) = ''
    or btrim(coalesce(p_guest_last_name, '')) = ''
    or btrim(coalesce(p_guest_email, '')) = ''
    or btrim(coalesce(p_guest_phone, '')) = '' then
    raise exception using
      errcode = '22023',
      message = 'INVALID_GUEST_DETAILS';
  end if;

  perform pg_advisory_xact_lock(p_room_type_id);

  select *
  into v_room
  from public.room_types
  where id = p_room_type_id
    and is_active;

  if not found then
    raise exception using
      errcode = 'P0002',
      message = 'ROOM_NOT_AVAILABLE';
  end if;

  select count(*)::integer
  into v_reserved
  from public.bookings as b
  where b.room_type_id = p_room_type_id
    and b.status in ('pending', 'confirmed')
    and b.arrival_date < p_departure_date
    and b.departure_date > p_arrival_date;

  if v_reserved >= v_room.total_units then
    raise exception using
      errcode = 'P0001',
      message = 'ROOM_SOLD_OUT';
  end if;

  v_total := v_room.nightly_rate * (p_departure_date - p_arrival_date);

  loop
    v_attempt := v_attempt + 1;
    v_confirmation := 'NYK-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10));

    begin
      insert into public.bookings (
        confirmation_code,
        room_type_id,
        guest_first_name,
        guest_last_name,
        guest_email,
        guest_phone,
        arrival_date,
        departure_date,
        status,
        nightly_rate,
        total_amount,
        currency
      )
      values (
        v_confirmation,
        v_room.id,
        btrim(p_guest_first_name),
        btrim(p_guest_last_name),
        lower(btrim(p_guest_email)),
        btrim(p_guest_phone),
        p_arrival_date,
        p_departure_date,
        'pending',
        v_room.nightly_rate,
        v_total,
        v_room.currency
      );
      exit;
    exception
      when unique_violation then
        if v_attempt >= 5 then
          raise;
        end if;
    end;
  end loop;

  return query
  select
    v_confirmation,
    'pending'::text,
    v_room.nightly_rate,
    v_total,
    v_room.currency,
    v_room.total_units - v_reserved - 1;
end;
$$;

create or replace function public.get_room_availability(
  p_arrival_date date,
  p_departure_date date
)
returns table (
  room_type_id bigint,
  reserved_units integer,
  available_units integer
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    r.id,
    count(b.id)::integer,
    greatest(r.total_units - count(b.id)::integer, 0)
  from public.room_types as r
  left join public.bookings as b
    on b.room_type_id = r.id
   and b.status in ('pending', 'confirmed')
   and b.arrival_date < p_departure_date
   and b.departure_date > p_arrival_date
  where r.is_active
    and p_arrival_date is not null
    and p_departure_date is not null
    and p_departure_date > p_arrival_date
  group by r.id, r.total_units;
$$;

alter table public.room_types enable row level security;
alter table public.room_images enable row level security;
alter table public.bookings enable row level security;

create policy "active room types are publicly readable"
on public.room_types
for select
to anon, authenticated
using (is_active);

create policy "admins manage room types"
on public.room_types
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "active room images are publicly readable"
on public.room_images
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.room_types
    where room_types.id = room_images.room_type_id
      and room_types.is_active
  )
);

create policy "admins manage room images"
on public.room_images
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "admins manage bookings"
on public.bookings
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

revoke all on table public.room_types from anon, authenticated;
revoke all on table public.room_images from anon, authenticated;
revoke all on table public.bookings from anon, authenticated;

grant select on table public.room_types to anon, authenticated;
grant select on table public.room_images to anon, authenticated;
grant insert, update, delete on table public.room_types to authenticated;
grant insert, update, delete on table public.room_images to authenticated;
grant select, insert, update, delete on table public.bookings to authenticated;

grant usage, select on sequence public.room_types_id_seq to authenticated;
grant usage, select on sequence public.room_images_id_seq to authenticated;
grant usage, select on sequence public.bookings_id_seq to authenticated;

revoke all on function public.set_updated_at() from public, anon, authenticated;
revoke all on function public.set_booking_timestamps() from public, anon, authenticated;
revoke all on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;

revoke all on function public.create_booking_request(
  bigint, text, text, text, text, date, date
) from public, anon, authenticated;
grant execute on function public.create_booking_request(
  bigint, text, text, text, text, date, date
) to service_role;

revoke all on function public.get_room_availability(date, date)
from public, anon, authenticated;
grant execute on function public.get_room_availability(date, date)
to service_role;

insert into public.room_types (
  slug,
  name,
  description,
  nightly_rate,
  currency,
  total_units,
  beds,
  bathrooms,
  is_active,
  display_order
)
values
  (
    'deluxe',
    'Deluxe Room',
    'A perfect blend of comfort and elegance with thoughtful amenities for a relaxing stay.',
    100,
    'USD',
    12,
    1,
    1,
    true,
    10
  ),
  (
    'royal',
    'Royal Room',
    'Unmatched luxury, generous space, and elevated details for an exceptional retreat.',
    120,
    'USD',
    8,
    1,
    1,
    true,
    20
  ),
  (
    'elite',
    'Elite Room',
    'The pinnacle of Nyakaju comfort, designed for guests seeking our most refined experience.',
    150,
    'USD',
    5,
    1,
    1,
    true,
    30
  )
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description,
  nightly_rate = excluded.nightly_rate,
  currency = excluded.currency,
  total_units = excluded.total_units,
  beds = excluded.beds,
  bathrooms = excluded.bathrooms,
  is_active = excluded.is_active,
  display_order = excluded.display_order;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'room-images',
  'room-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "admins can read room image objects"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'room-images'
  and (select public.is_admin())
);

create policy "admins can upload room image objects"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'room-images'
  and (select public.is_admin())
);

create policy "admins can update room image objects"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'room-images'
  and (select public.is_admin())
)
with check (
  bucket_id = 'room-images'
  and (select public.is_admin())
);

create policy "admins can delete room image objects"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'room-images'
  and (select public.is_admin())
);
